name: Deploy to GitHub Pages

on:
  # 当推送到 main 分支时触发
  push:
    branches: [ main ]
  
  # 允许手动触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个部署同时进行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 部署任务
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v4
      
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传整个仓库
          path: '.'
      
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

